# this file has been generated by update-versions.sh
# for DSP, API, APP, Ingest, see https://github.com/dasch-swiss/ops-deploy/blob/main/versions/RELEASE.json
# for TOOLS, see https://github.com/dasch-swiss/dsp-tools/releases
# for META, see https://github.com/dasch-swiss/dsp-meta/tags (NB: tags start with 'dsp-meta-')
DSP := "2025.03.03"
API := "v31.9.1"
APP := "v11.27.0"
TOOLS := "v12.0.0"
INGEST := "v0.18.8"
META := "dsp-meta-v2.3.7"
