# this file has been generated by update-versions.sh
# for DSP, API (includes INGEST), APP, see https://github.com/dasch-swiss/ops-deploy/blob/main/versions/RELEASE.json
# for TOOLS, see https://github.com/dasch-swiss/dsp-tools/releases
# for META, see https://github.com/dasch-swiss/dsp-meta/tags (NB: tags start with 'dsp-meta-')
DSP := "2025.12.01"
API := "v33.1.1"
APP := "v12.2.3"
TOOLS := "18.3.0"
META := "dsp-meta-v2.4.2"
