openapi: 3.1.0
info:
  title: dsp-ingest-monitoring
  version: v0.17.0
servers:
- url: http://localhost:3340
  description: Local development server
- url: https://ingest.dasch.swiss
  description: Production server
paths:
  /info:
    get:
      tags:
      - monitoring
      operationId: getInfo
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoEndpointResponse'
              example:
                name: dsp-ingest
                version: v0.17.0
                scalaVersion: 3.3.4
                sbtVersion: 1.10.6
                buildTime: 2025-01-23 12:53:07.883+0000
                gitCommit: bd4af171f41a79c0a31cfd9622111aee1af9a04f
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '403':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '409':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conflict'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
        '503':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unhealthy'
  /health:
    get:
      tags:
      - monitoring
      operationId: getHealth
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AggregatedHealth'
              example:
                status: UP
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '403':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '409':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conflict'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
        '503':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unhealthy'
  /metrics:
    get:
      tags:
      - monitoring
      operationId: getMetrics
      responses:
        '200':
          description: ''
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '403':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '409':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conflict'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
        '503':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unhealthy'
components:
  schemas:
    AggregatedHealth:
      title: AggregatedHealth
      type: object
      required:
      - status
      properties:
        status:
          $ref: '#/components/schemas/Status'
        components:
          $ref: '#/components/schemas/Map_Health'
    Argument:
      title: Argument
      type: object
      required:
      - argument
      - reason
      properties:
        argument:
          type: string
        reason:
          type: string
    BadRequest:
      title: BadRequest
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Argument'
    Conflict:
      title: Conflict
      type: object
      required:
      - reason
      properties:
        reason:
          type: string
    DOWN:
      title: DOWN
      type: object
    Forbidden:
      title: Forbidden
      type: object
      required:
      - reason
      properties:
        reason:
          type: string
    Health:
      title: Health
      type: object
      required:
      - status
      properties:
        status:
          $ref: '#/components/schemas/Status'
    InfoEndpointResponse:
      title: InfoEndpointResponse
      type: object
      required:
      - name
      - version
      - scalaVersion
      - sbtVersion
      - buildTime
      - gitCommit
      properties:
        name:
          type: string
        version:
          type: string
        scalaVersion:
          type: string
        sbtVersion:
          type: string
        buildTime:
          type: string
        gitCommit:
          type: string
    InternalServerError:
      title: InternalServerError
      type: object
      required:
      - errorMessage
      properties:
        errorMessage:
          type: string
    Map_Health:
      title: Map_Health
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Health'
    NotFound:
      title: NotFound
      type: object
      required:
      - id
      - type
      properties:
        id:
          type: string
        type:
          type: string
    Status:
      title: Status
      oneOf:
      - $ref: '#/components/schemas/DOWN'
      - $ref: '#/components/schemas/UP'
    UP:
      title: UP
      type: object
    Unauthorized:
      title: Unauthorized
      type: object
      required:
      - reason
      properties:
        reason:
          type: string
    Unhealthy:
      title: Unhealthy
      type: object
      required:
      - status
      properties:
        status:
          $ref: '#/components/schemas/Status'
        components:
          $ref: '#/components/schemas/Map_Health'
