name: deploy

on:
  pull_request:
    types: 
        - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: interrupt if PR title does not start with "deploy" prefix
        run: |
          import re, os, sys
          if not re.match(r"^deploy: .+", os.environ["PR_TITLE"]):
              sys.exit(1)
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        shell: python
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Grab commits from submodules
        run: |
          make init-submodules
          make update-submodules
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install graphviz
      - name: build graphviz figures
        run: make graphvizfigures
      - name: Install just
        uses: extractions/setup-just@v1
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Update OpenAPI docs
        run: make openapi-update
      - name: Build docs in strict mode
        run: make deploy
