name: deploy

on:
  push:
    branches: 
        - main

jobs:
  deploy:
    if: startsWith(github.event.head_commit.message, 'deploy')
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Authenticate with GitHub
        env:
          GH_PAT: ${{ secrets.DASCHBOT_PAT }}
        run: |
          echo "https://${GH_PAT}:@github.com" > ~/.git-credentials
          git config --global credential.helper store
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessary for git-revision-date-localized-plugin
          submodules: 'recursive'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install dependencies
        run: sudo apt-get install graphviz
      - name: build graphviz figures
        run: make graphvizfigures
      - name: Deploy docs
        run: make deploy
