name: deploy

on:
  push:
    branches: 
        - main

jobs:
  deploy:
    if: startsWith(github.event.head_commit.message, 'deploy')
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessary for git-revision-date-localized-plugin
          submodules: 'recursive'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python3 -m venv .venv
          make install-requirements
          sudo apt-get install graphviz
      - name: build graphviz figures
        run: make graphvizfigures
      - name: Install just
        uses: extractions/setup-just@v1
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Update OpenAPI docs
        run: make openapi-update
      - name: Deploy docs
        run: make deploy
