name: pr-checks

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessary for git-revision-date-localized-plugin
          submodules: 'recursive'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install dependencies
        run: sudo apt-get install graphviz
      - name: build graphviz figures
        run: make graphvizfigures
      - name: Install just
        uses: extractions/setup-just@v2
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Update OpenAPI docs
        run: make openapi-update
      - name: Build docs with mkdocs in strict mode
        run: uv run mkdocs build --strict --verbose
      - name: Call the Make recipe (which uses mike, which is used to publish the docs)
        run: make build
